// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khcrhgpkmvwnwqeqknuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtoY3JoZ3BrbXZ3bndxZXFrbnV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MjM2MDYsImV4cCI6MjA2MDI5OTYwNn0.KYFYYZCzI_UTAiXgp4riCXec8ilJ5WOybKHY1ndlUkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);